#!/bin/bash

cd 20M0274
cd LOGS
rm history.data
cd ../
./mk
./rn

cd 30M0269
cd LOGS
rm history.data
cd ../
./mk
./rn

cd ../40M0265
cd LOGS
rm history.data
cd ../
./mk
./rn

cd ../50M0264
cd LOGS
rm history.data
cd ../
./mk
./rn

cd ../60M0262
cd LOGS
rm history.data
cd ../
./mk
./rn
cd ../

echo "TERMINOU PORRAA!!"
